### ISSUE TITLE
street.Length не равен количеству элементов в data.street

### ISSUE THREAD

**Issue by jimdi** [lnl122/dgdat_parse#3]
для примера брал Kurgan
data.street.Length - возвращает 750
```
for (int str_idx = 0; str_idx < data.street.Length; str_idx++)
{
  tbLog.AppendText(data.street[str_idx].name + "\r\n");
}
```
однако если перебирать улицы таким способом, то их 748
ЧЯДНТ?

**Comment by lnl122** [comment]
в списках названий улиц, зданий, городов и прочих, имеющих тестовое обозначение в базах некоторых городов содержатся пустые пустые строки. Проверял для Алматы, Красноярска, Альметьевска на улицах и алиасах улиц. Во всех городах от одного до примерно десяти пустых элементов.

Также, проверял ссылки на пустые названия улиц - не выявил.

Предполагаю, что это артефакты, появившиеся во время сборки файла базы. Работе это не мешает.

) ЧЯДНТ:
for (int str_idx = 0; str_idx < data.street.Length; str_idx++)
{
  tbLog.AppendText(str_idx.ToString() + " begin_" + data.street[str_idx].name + "_end\r\n");
}
- их будет видно.
